services:
    dockerlink:
        build:
            context: .
        ports:
            - "8001:80"
        env_file:
            - .env
        volumes:
            - //var/run/docker.sock:/var/run/docker.sock